In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
import pickle

In [38]:
df=pd.read_csv('adv.xlsx.csv')

In [39]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [40]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [41]:
d= ProfileReport(df)

In [57]:
d.to_widgets()

In [43]:
d.to_file('linera_test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [44]:
x=df[['TV']]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [46]:
y= df['Sales']
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [47]:
from sklearn.linear_model import LinearRegression

In [48]:
linear = LinearRegression()

In [49]:
linear.fit(x,y)

LinearRegression()

In [50]:
linear.predict([[45]])

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [55]:
linear.intercept_  ##intercept means value of m

6.9748214882298925

In [56]:
linear.coef_  ##value of c in y=mx+c

array([0.05546477])

In [ ]:
##another way of calling model from saved file and predicting output of TV VALUE 45

In [51]:
pickle.dump(linear,open('pickle_dump.sav','wb'))  ##saving our model in byte form

In [52]:
saved_model= pickle.load(open('pickle_dump.sav','rb'))  ##retreiving save dmodel from file 

In [53]:
saved_model.predict([[45]]) ##it will predict our output sales for tv value 45

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [54]:
saved_model.score(x,y) ##accuracy of our model

0.8121757029987414